name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: sbtscala/scala-sbt:graalvm-community-22.0.1_1.10.11_3.6.4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #      - name: Formatting check
      #        run: sbt fmtCheck

      - name: Compile & test
        run: sbt compile test

      - name: Publish
        run: sbt publish
